# Generated by Django 4.0.4 on 2022-05-18 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contributiontype_alter_commodity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributiontype',
            name='contributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='main.contributor'),
        ),
    ]
