# Generated by Django 4.0.4 on 2022-05-18 11:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_contributiontype_contributor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributiontype',
            name='contributor',
        ),
        migrations.AddField(
            model_name='contributor',
            name='contribution_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributors', to='main.contributiontype', verbose_name='Contribution Type'),
        ),
        migrations.AddField(
            model_name='contributor',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributors', to='main.mediabase'),
        ),
        migrations.AddField(
            model_name='mediabase',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail1',
            field=models.ImageField(blank=True, null=True, upload_to='video/thumbnails/'),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail2',
            field=models.ImageField(blank=True, null=True, upload_to='video/thumbnails/'),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail3',
            field=models.ImageField(blank=True, null=True, upload_to='video/thumbnails/'),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail4',
            field=models.ImageField(blank=True, null=True, upload_to='video/thumbnails/'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_file_15',
            field=models.FileField(blank=True, null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov'])], verbose_name='15 Seconds Preview'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_file_30',
            field=models.FileField(blank=True, null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov'])], verbose_name='30 Seconds Preview'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_file_60',
            field=models.FileField(blank=True, null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov'])], verbose_name='6o Seconds Preview'),
        ),
        migrations.AlterField(
            model_name='contributiontype',
            name='name',
            field=models.CharField(db_index=True, max_length=256, unique=True, verbose_name='Contribution Type'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='remarks',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov'])], verbose_name='Full Video'),
        ),
    ]
