# Generated by Django 4.0.4 on 2022-05-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_mediabase_agency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediabase',
            name='agency',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True, unique=True, verbose_name='Agency'),
        ),
    ]
