# Generated by Django 4.0.4 on 2022-05-19 06:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_mediabase_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediabase',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 19, 6, 31, 45, 450390, tzinfo=utc), verbose_name='Published Date'),
        ),
    ]
