# Generated by Django 4.0.4 on 2022-05-19 07:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_mediabase_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediabase',
            name='genre',
        ),
        migrations.AddField(
            model_name='video',
            name='genre',
            field=models.ManyToManyField(related_name='media', to='main.genre', verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='mediabase',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 19, 7, 1, 59, 261808, tzinfo=utc), verbose_name='Published Date'),
        ),
    ]
