# Generated by Django 4.0.4 on 2022-05-19 09:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_video_vtt_url_alter_mediabase_published_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='genre',
            new_name='genres',
        ),
        migrations.AlterField(
            model_name='mediabase',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 19, 9, 38, 38, 52441, tzinfo=utc), verbose_name='Published Date'),
        ),
    ]
