# Generated by Django 4.0.4 on 2022-05-20 05:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_genre_video_genres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediabase',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 20, 5, 18, 50, 894114, tzinfo=utc), verbose_name='Published Date'),
        ),
    ]
