# Generated by Django 4.0.4 on 2022-05-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_agency_remove_mediabase_published_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediabase',
            name='description',
        ),
        migrations.RemoveField(
            model_name='video',
            name='stream_url',
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='Youtube URL'),
        ),
    ]
