# Generated by Django 4.0.4 on 2022-05-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_mediabase_description_remove_video_stream_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediabase',
            name='agency',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Agency'),
        ),
    ]
