# Generated by Django 4.0.4 on 2022-05-20 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_mediabase_agency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards', to='main.mediabase'),
        ),
        migrations.AlterField(
            model_name='mediabase',
            name='views',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Views'),
        ),
    ]
