# Generated by Django 4.0.4 on 2022-05-22 06:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_video_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediabase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediabase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
