# Generated by Django 4.0.4 on 2022-05-22 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_commodity_related_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodity',
            name='related_media',
        ),
    ]
