# Generated by Django 4.0.4 on 2022-05-24 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_commodity_related_media'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='award',
            unique_together=set(),
        ),
    ]
