# Generated by Django 4.0.4 on 2022-05-25 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediabase',
            name='agency',
        ),
    ]
