# Generated by Django 4.0.4 on 2022-05-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_remove_mediabase_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediabase',
            name='agency',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Agency'),
        ),
    ]
