# Generated by Django 4.0.4 on 2022-05-25 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_image_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='media',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='main.mediabase'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contributor',
            name='media',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='main.mediabase'),
            preserve_default=False,
        ),
    ]
