# Generated by Django 4.0.4 on 2022-05-26 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_award_media_alter_contributor_media'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='award',
            unique_together={('title', 'year')},
        ),
    ]
