# Generated by Django 4.0.4 on 2022-05-26 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_award_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediabase',
            name='media_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='media', to='main.mediatype', verbose_name='Media Type'),
        ),
    ]
