# Generated by Django 4.0.4 on 2022-05-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediatype',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
