# Generated by Django 4.0.4 on 2022-05-30 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_award_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='thumbnail1',
        ),
        migrations.RemoveField(
            model_name='video',
            name='thumbnail2',
        ),
        migrations.RemoveField(
            model_name='video',
            name='thumbnail3',
        ),
        migrations.RemoveField(
            model_name='video',
            name='thumbnail4',
        ),
        migrations.AlterField(
            model_name='agency',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='VideoThumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='video/thumbnails/')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='main.video')),
            ],
        ),
    ]
