# Generated by Django 4.0.4 on 2022-05-30 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_remove_video_thumbnail1_remove_video_thumbnail2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediabase',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='main.agency'),
        ),
    ]
