# Generated by Django 4.0.4 on 2022-06-06 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_mediabase_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediabase',
            name='type',
            field=models.CharField(choices=[('V', 'Video'), ('I', 'Image')], default='V', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mediabase',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='main.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='mediabase',
            name='media_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='main.mediatype', verbose_name='Media Type'),
        ),
    ]
